export const states = [
  'Alabama',
  'Alaska',
  'Arizona',
  'Arkansas',
  'California',
  'Colorado',
  'Connecticut',
  'Delaware',
  'Florida',
  'Georgia',
  'Hawaii',
  'Idaho',
  'Illinois',
  'Indiana',
  'Iowa',
  'Kansas',
  'Kentucky',
  'Louisiana',
  'Maine',
  'Maryland',
]

export const cities = [
  'Tokyo',
  'New York City',
  'London',
  'Paris',
  'Sydney',
  'Rio de Janeiro',
  'Moscow',
  'Toronto',
  'Dubai',
  'Mumbai',
  'Berlin',
  'Cape Town',
  'Singapore',
  'Mexico City',
  'Tokyo',
  'Seoul',
  'Amsterdam',
  'Rome',
  'Istanbul',
  'Bangkok',
]

export const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua',
  'Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
]

export const pickupHoursOptions = [
  '12:00 AM',
  '12:30 AM',
  '1:00 AM',
  '1:30 AM',
  '2:00 AM',
  '2:30 AM',
  '3:00 AM',
  '3:30 AM',
  '4:00 AM',
  '4:30 AM',
  '5:00 AM',
  '5:30 AM',
  '6:00 AM',
  '6:30 AM',
  '7:00 AM',
  '7:30 AM',
  '8:00 AM',
  '8:30 AM',
  '9:00 AM',
  '9:30 AM',
  '10:00 AM',
  '10:30 AM',
  '11:00 AM',
  '11:30 AM',
]

export const pickupDayOptions = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
  'Sunday',
]

export const galleryImages = [
  {
    id: 1,
    title: 'Image 1',
    url: 'https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900',
  },
  {
    id: 2,
    title: 'Image 2',
    url: 'https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-1-2.jpg',
  },
  {
    id: 3,
    title: 'Image 3',
    url: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/02/05/Baked-Feta-Pasta-4_s4x3.jpg.rend.hgtvcom.616.493.suffix/1615916524567.jpeg',
  },
  {
    id: 4,
    title: 'Image 4',
    url: 'https://img.freepik.com/free-photo/grilled-sandwich-with-bacon-fried-egg-tomato-lettuce-served-wooden-cutting-board_1150-42571.jpg?w=2000',
  },
  {
    id: 5,
    title: 'Image 5',
    url: 'https://cafedelites.com/wp-content/uploads/2018/01/Mamas-Best-Lasagna-IMAGE-43.jpg',
  },
  {
    id: 6,
    title: 'Image 6',
    url: 'https://liliebakery.fr/wp-content/uploads/2021/03/Recette-donuts-Lilie-Bakery.jpg',
  },
]

export const HomePageBackgrounds = [
  {
    id: 1,
    title: 'your baking connection',
    subTitle: 'The online marketplace for home bakeries. We connect home bakers to local buyers.',
    url: '/Images/homepage-background.webp',
  },
  {
    id: 2,
    title: 'Bake With Passion',
    subTitle:
      'Unleash your inner pastry chef. Connect with local buyers through our online marketplace for home bakers.',
    url: 'https://assets.bonappetit.com/photos/57acad861b3340441497511a/16:9/w_2560%2Cc_limit/chocolate-or-vanilla-cream-cheese-frosting.jpg',
  },
  {
    id: 3,
    title: 'Deliciously Fresh',
    subTitle: 'From our ovens to you, savor the taste of handcrafted baked treats.',
    url: 'https://media.istockphoto.com/id/1141009146/photo/cheerful-polka-dot-cupcakes.jpg?s=612x612&w=0&k=20&c=hVnMNFiw93Dg8fBkR7GMBFgzdJyWyBymhTECvixaYw4=',
  },
  {
    id: 4,
    title: 'Taste the Difference',
    subTitle:
      'Handcrafted perfection, one bite at a time. Discover the delectable creations from our talented bakers.',
    url: 'https://w0.peakpx.com/wallpaper/477/651/HD-wallpaper-cupcakes-dessert-cream-sweet.jpg',
  },
]

export const accordionData = [
  {
    id: 0,
    title: 'Is there a free trial available?',
    content:
      'Yes, you can try us for free for 30 days. If you want, we’ll provide you with a free, personalized 30-minute onboarding call to get you up and running as soon as possible.',
  },
  {
    id: 1,
    title: 'Can I change my plan later?',
    content: `In fractional property ownership, you buy a specific quantity or fraction of a property. You can choose the amount you can afford based on the total available. The property is managed by professionals serving as trustees, and you can earn dividends(if property is on lease/let) and potentially sell a fraction or all of your units in the future. As co-owners you all have control on what happens to the property through weighted votes based on your holding.`,
  },
  {
    id: 2,
    title: 'What is your cancellation policy?',
    content: `Fractional property investing offers several benefits, including the ability to diversify your real estate portfolio by owning fractions of different properties. It allows you to invest in high-value properties that may have been otherwise unaffordable. Additionally, fractional property investing provides you liquidity, as you can sell your fractions/units when needed.
      `,
  },
  {
    id: 3,
    title: `Can other info be added to an invoice?`,
    content: `If the property is available for letting, you can earn dividends based on your holding. Dividends are distributed based on the leasing income generated by the property, allowing you to earn regular income from your investment.`,
  },
  {
    id: 4,
    title: `How does billing work?`,
    content: `On the Partown fractional property marketplace, you have the option to sell your units by just listing the quantity you want to sell at a particular price. It is advisable to sell as close as possible to the market value so you protect your returns and have a quick turnaround. You can choose to sell only the quantities that meet your immediate needs, this provides flexibility and just-in-time liquidity.`,
  },
  {
    id: 5,
    title: `How do I change my account email?`,
    content: `This is easy, you just need to add a bank account to your profile and specify the amount you intend to withdraw. We will send you a notification to verify by email or text message before wiring the proceeds to your account. The whole process takes about two(2) days.`,
  },
]

export const ReviewCardsData = [
  {
    id: 1,
    name: 'John Doe',
    image:
      'https://image.winudf.com/v2/image1/bmV0LndsbHBwci5naXJsc19wcm9maWxlX3BpY3R1cmVzX3NjcmVlbl8xXzE2Njc3MjczMTZfMDE3/screen-1.webp?fakeurl=1&type=.webp',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
  {
    id: 2,
    name: 'Sara Austin',
    image:
      'https://image.winudf.com/v2/image1/bmV0LndsbHBwci5naXJsc19wcm9maWxlX3BpY3R1cmVzX3NjcmVlbl8xXzE2Njc3MjczMTZfMDE3/screen-1.webp?fakeurl=1&type=.webp',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod,',
  },
  {
    id: 3,
    name: 'robert kent',
    image:
      'https://image.winudf.com/v2/image1/bmV0LndsbHBwci5naXJsc19wcm9maWxlX3BpY3R1cmVzX3NjcmVlbl8xXzE2Njc3MjczMTZfMDE3/screen-1.webp?fakeurl=1&type=.webp',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
  {
    id: 4,
    name: 'Suzy Clark',
    image:
      'https://image.winudf.com/v2/image1/bmV0LndsbHBwci5naXJsc19wcm9maWxlX3BpY3R1cmVzX3NjcmVlbl8xXzE2Njc3MjczMTZfMDE3/screen-1.webp?fakeurl=1&type=.webp',
    content:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue, et ultricies velit nisl vitae nunc.',
  },
]

export const profileNavigation = [
  {
    id: 1,
    title: 'My Profile',
    icon: '/Images/user.svg',
  },
  {
    id: 2,
    title: 'Payment details',
    icon: '/Images/payment-details.svg',
  },
  {
    id: 3,
    title: 'purchase history',
    icon: '/Images/history.svg',
  },
  {
    id: 4,
    title: 'settings',
    icon: '/Images/setting.svg',
  },
  {
    id: 5,
    title: 'help',
    icon: '/Images/help.svg',
  },
  {
    id: 6,
    title: 'logout',
    icon: '/Images/logout.svg',
  },
]

export const weOfferData = [
  {
    id: 1,
    title: 'cake',
    image: '/Images/we-offer-1.svg',
  },
  {
    id: 2,
    title: 'bread',
    image: '/Images/we-offer-2.svg',
  },
  {
    id: 3,
    title: 'decorated cookies',
    image: '/Images/we-offer-3.svg',
  },
  {
    id: 4,
    title: 'decorated cakes',
    image: '/Images/we-offer-4.svg',
  },
  {
    id: 5,
    title: 'decorated cupcakes',
    image: '/Images/we-offer-4.svg',
  },
  {
    id: 6,
    title: 'chocolate',
    image: '/Images/we-offer-4.svg',
  },
  {
    id: 7,
    title: 'sandwich',
    image: '/Images/we-offer-4.svg',
  },
]

export const ProductsCatagory = [
  'All',
  'Cakes',
  'Bread',
  'Decorated Cookies',
  'Decorated Cakes',
  'Decorated Cupcakes',
  'Chocolate',
  'Sandwich',
  'Pizza',
  'Burger',
  'Doughnut',
  'Ice Cream',
  'Cupcakes',
  'Biscuits',
  'Pies',
  'Pastries',
  'Puddings',
  'Muffins',
  'Brownies',
  'Tarts',
  'Pancakes',
  'Waffles',
  'Crepes',
  'Pretzels',
  'Bagels',
  'Scones',
  'Croissants',
]

export const steps = [
  {
    label: 'Sign Up',
    description: `Sign up with just a click! No fuss, no worries, it’s that easy!`,
  },
  {
    label: 'Enter Shop Details',
    description: 'Sign in now: Quick and effortless entry to all your favorite features.',
  },
  {
    label: 'Create Shop',
    description: `Our advanced search filters make it easy to find what you’re looking for. Start your search now!`,
  },
]

export const ProductTypes = [
  'All',
  'Cakes',
  'Bread',
  'Decorated Cookies',
  'Decorated Cakes',
  'Decorated Cupcakes',
  'Chocolate',
  'Sandwich',
  'Pizza',
  'Burger',
  'Doughnut',
  'Ice Cream',
  'Cupcakes',
  'Biscuits',
  'Pies',
  'Pastries',
  'Puddings',
  'Muffins',
  'Brownies',
  'Tarts',
  'Pancakes',
  'Waffles',
  'Crepes',
  'Pretzels',
  'Bagels',
  'Scones',
  'Croissants',
]

export const GalleryNavigation = [
  {
    id: 1,
    title: 'Available Products',
  },
  {
    id: 2,
    title: 'Gallery of work',
  },
  {
    id: 3,
    title: 'Terms & Conditions',
  },
  {
    id: 4,
    title: 'Allergen Information',
  },
  {
    id: 5,
    title: 'reviews',
  },
]

export const ProductDetailNavigationTabs = [
  {
    id: 1,
    title: 'Description',
  },
  {
    id: 2,
    title: 'reviews',
  },
  {
    id: 3,
    title: 'FAQs',
  },
]

export const GalleryProductsData = [
  {
    id: 1,
    title: 'ring pizza',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image: 'https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900',
    oldPrice: '10.00',
    newPrice: '8.00',
    category: 'pizza',
  },
  {
    id: 2,
    title: 'tasty burger',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image:
      'https://www.chilitochoc.com/wp-content/uploads/2020/05/crispy-chicken-burger-e1615289026561.jpg',
    oldPrice: '10.00',
    newPrice: '8.00',
    category: 'burger',
  },
  {
    id: 3,
    title: 'nutella doughnut',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image: 'https://liliebakery.fr/wp-content/uploads/2021/03/Recette-donuts-Lilie-Bakery.jpg',
    oldPrice: '15.00',
    newPrice: '12.00',
    category: 'doughnut',
  },
  {
    id: 4,
    title: 'ice cream',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image:
      'https://bromabakery.com/wp-content/uploads/2020/05/chocolate-oreo-ice-cream-3-1067x1600.webp',
    oldPrice: '10.00',
    newPrice: '8.00',
    category: 'ice cream',
  },
  {
    id: 5,
    title: 'cupcake',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image:
      'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_744,ar_5:4/v1/img/recipes/13/37/67/pic5UBrag.jpg',
    oldPrice: '10.00',
    newPrice: '8.00',
    category: 'cupcake',
  },
  {
    id: 6,
    title: 'biscuit',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, diam id tincidunt dapibus, magna libero sodales augue,',
    image: 'https://5.imimg.com/data5/WJ/RT/XR/ANDROID-59043477/product-jpeg-500x500.jpg',
    oldPrice: '10.00',
    newPrice: '8.00',
    category: 'biscuit',
  },
]

export const GalleryShopImages = [
  {
    id: 1,
    title: 'pizza',
    url: 'https://static.toiimg.com/thumb/53110049.cms?width=1200&height=900',
  },
  {
    id: 2,
    title: 'donuts',
    url: 'https://liliebakery.fr/wp-content/uploads/2021/03/Recette-donuts-Lilie-Bakery.jpg',
  },
  {
    id: 3,
    title: 'burger',
    url: 'https://www.chilitochoc.com/wp-content/uploads/2020/05/crispy-chicken-burger-e1615289026561.jpg',
  },
  {
    id: 4,
    title: 'xyz',
    url: 'https://img.sndimg.com/food/image/upload/f_auto,c_thumb,q_55,w_744,ar_5:4/v1/img/recipes/13/37/67/pic5UBrag.jpg',
  },
  {
    id: 5,
    title: 'veggie-burger',
    url: 'https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-1-2.jpg',
  },
  {
    id: 6,
    title: 'pasta',
    url: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/02/05/Baked-Feta-Pasta-4_s4x3.jpg.rend.hgtvcom.616.493.suffix/1615916524567.jpeg',
  },
  {
    id: 7,
    title: 'sandwich',
    url: 'https://img.freepik.com/free-photo/grilled-sandwich-with-bacon-fried-egg-tomato-lettuce-served-wooden-cutting-board_1150-42571.jpg?w=2000',
  },
  {
    id: 8,
    title: 'lasagna',
    url: 'https://cafedelites.com/wp-content/uploads/2018/01/Mamas-Best-Lasagna-IMAGE-43.jpg',
  },
  {
    id: 9,
    title: 'cookies',
    url: 'https://5.imimg.com/data5/WJ/RT/XR/ANDROID-59043477/product-jpeg-500x500.jpg',
  },
  {
    id: 10,
    title: 'veggie-burger-7',
    url: 'https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-1-2.jpg',
  },
  {
    id: 11,
    title: 'pasta-7',
    url: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/02/05/Baked-Feta-Pasta-4_s4x3.jpg.rend.hgtvcom.616.493.suffix/1615916524567.jpeg',
  },
  {
    id: 12,
    title: 'sandwich-7',
    url: 'https://img.freepik.com/free-photo/grilled-sandwich-with-bacon-fried-egg-tomato-lettuce-served-wooden-cutting-board_1150-42571.jpg?w=2000',
  },
  // {
  //   id: 13,
  //   title: 'lasagna-7',
  //   url: 'https://cafedelites.com/wp-content/uploads/2018/01/Mamas-Best-Lasagna-IMAGE-43.jpg',
  // },
  // {
  //   id: 14,
  //   title: 'veggie-burger-3',
  //   url: 'https://www.noracooks.com/wp-content/uploads/2023/04/veggie-burgers-1-2.jpg',
  // },
  // {
  //   id: 15,
  //   title: 'pasta-3',
  //   url: 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2021/02/05/Baked-Feta-Pasta-4_s4x3.jpg.rend.hgtvcom.616.493.suffix/1615916524567.jpeg',
  // },
  // {
  //   id: 16,
  //   title: 'sandwich-3',
  //   url: 'https://img.freepik.com/free-photo/grilled-sandwich-with-bacon-fried-egg-tomato-lettuce-served-wooden-cutting-board_1150-42571.jpg?w=2000',
  // },
  // {
  //   id: 17,
  //   title: 'lasagna-3',
  //   url: 'https://cafedelites.com/wp-content/uploads/2018/01/Mamas-Best-Lasagna-IMAGE-43.jpg',
  // },
]

export const YourProfileCardItemData = [
  {
    id: 1,
    title: 'Purchase History',
    description: 'Recording and tracking transactions and monitoring cash flow',
    image: '/Images/profile-purchase-history.svg',
  },
  {
    id: 2,
    title: 'Ratings and Reviews',
    description: 'Customer management, financial and inventory management',
    image: '/Images/profile-rating-and-reviews.svg',
  },
  {
    id: 3,
    title: 'Preferences',
    description: 'Order confirmation, payment reminder, account balance update',
    image: '/Images/profile-preferences.svg',
  },
  // {
  //   id: 4,
  //   title: 'Privacy Setting',
  //   description: 'Track, return, cancel an order, download invoice or buy again',
  //   image: '/Images/profile-privacy-settings.svg',
  // },
  {
    id: 5,
    title: 'Payment Details',
    description: 'Customer management, financial and inventory management',
    image: '/Images/profile-payment-details.svg',
  },
  {
    id: 6,
    title: 'Settings',
    description: 'Order confirmation, payment reminder, account balance update',
    image: '/Images/profile-settings.svg',
  },
  {
    id: 7,
    title: 'Help',
    description: 'Track, return, cancel an order, download invoice or buy again ',
    image: '/Images/profile-help.svg',
  },
]

export const DurationOptions = [
  'past 24 hours',
  'past 1 week',
  'past 1 month',
  'past 3 months',
  'past 6 months',
  'past 1 year',
]

export const BakeryNameOptions = [
  'Bakery 1',
  'Bakery 2',
  'Bakery 3',
  'Bakery 4',
  'Bakery 5',
  'Bakery 6',
  'Bakery 7',
  'Bakery 8',
  'Bakery 9',
  'Bakery 10',
  'Bakery 11',
  'Bakery 12',
  'Bakery 13',
  'Bakery 14',
  'Bakery 15',
]

export const RatingOptions = ['1 star', '2 star', '3 star', '4 star', '5 star']

export const dietaryRestrictionOptions = [
  'Gluten Free',
  'Dairy Free',
  'Nut Free',
  'Egg Free',
  'Soy Free',
  'Sugar Free',
  'Vegan',
  'Vegetarian',
  'Keto',
  'Paleo',
  'Halal',
  'Kosher',
]

export const bakingStyleOptions = [
  'Baking',
  'Cake Decorating',
  'Cupcake Decorating',
  'Cookie Decorating',
  'Bread Making',
  'Pastry Making',
  'Chocolate Making',
  'Sugar Craft',
  'Cake Pops',
  'Cake Balls',
]

export const orderItemsData = [
  {
    id: 1,
    title: 'ring pizza',
    price: '10',
    quantity: '1',
  },
  {
    id: 2,
    title: 'tasty burger',
    price: '10',
    quantity: '1',
  },
  {
    id: 3,
    title: 'nutella doughnut',
    price: '15',
    quantity: '1',
  },
  {
    id: 4,
    title: 'ice cream',
    price: '10',
    quantity: '1',
  },
]

export const paymentMethods = [
  {
    id: 1,
    title: 'Google-Pay-icon',
    img: '/Images/google-pay-icon.svg',
  },
  {
    id: 2,
    title: 'Paypal-icon',
    img: '/Images/paypal-icon.svg',
  },
  {
    id: 3,
    title: 'Apple-Pay-icon',
    img: '/Images/apple-pay-icon.svg',
  },
  {
    id: 4,
    title: 'Visa-icon',
    img: '/Images/visa-icon.svg',
  },
  {
    id: 5,
    title: 'Master-Card-icon',
    img: '/Images/master-card-icon.svg',
  },
  {
    id: 6,
    title: 'Stripe-icon',
    img: '/Images/stripe-icon.svg',
  },
]
