stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

# THIS IS THE PIPELINE FOR STAGING BRANCH
build-staging: # This job runs in the build stage, which runs first.
  stage: build
  only:
    - staging
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
    - echo "$ENV_FILE_STAGING" > .env
  script:
    - pwd
#    - ls
    - cat .env
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "rm -rf sp-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "git clone https://gitlab+deploy-token-2328416:LYofLbnK4avwKnGMhvh-@gitlab.com/Codistan/yourbakingconnection/baker-seller-panel.git sp-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && git checkout staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && rm -rf .env"
    - scp -r /builds/Codistan/yourbakingconnection/baker-seller-panel/.env $HOSTNAME@$PUBLIC_KEY:/home/ubuntu/sp-staging
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && sed -i 's/next start/PORT=4002 next start/g' package.json"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && npm install --legacy-peer-deps"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && npm run build"


deploy-staging:
  only:
    - staging
  stage: deploy
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
#    - echo "$ENV_FILE_STAGING" > .env
  script:
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && git checkout staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && pm2 delete sp-staging"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-staging && pm2 start 'npm start' --name sp-staging"


# THIS IS THE PIPELINE FOR MAIN BRANCH
build-main: # This job runs in the build stage, which runs first.
  stage: build
  only:
    - main
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
    - echo "$ENV_FILE_MAIN" > .env
  script:
    - pwd
#    - ls
    - cat .env
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "rm -rf sp-main"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "git clone https://gitlab+deploy-token-2328416:LYofLbnK4avwKnGMhvh-@gitlab.com/Codistan/yourbakingconnection/baker-seller-panel.git sp-main"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && git checkout main"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && rm -rf .env"
    - scp -r /builds/Codistan/yourbakingconnection/baker-seller-panel/.env $HOSTNAME@$PUBLIC_KEY:/home/ubuntu/sp-main
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && sed -i 's/next start/PORT=4001 next start/g' package.json"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && npm install --legacy-peer-deps"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && npm run build"

deploy-main:
  only:
    - main
  stage: deploy
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
#    - echo "$ENV_FILE_STAGING" > .env
  script:
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && git checkout main"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && pm2 delete sp-main"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-main && pm2 start 'npm start' --name sp-main"

# THIS IS THE PIPELINE FOR STAGING BRANCH
build-test: # This job runs in the build stage, which runs first.
  stage: build
  only:
    - test
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
    - echo "$ENV_FILE_TEST" > .env
  script:
    - pwd
#    - ls
    - cat .env
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "rm -rf sp-test"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "git clone https://gitlab+deploy-token-2328416:LYofLbnK4avwKnGMhvh-@gitlab.com/Codistan/yourbakingconnection/baker-seller-panel.git sp-test"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && git checkout test"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && rm -rf .env"
    - scp -r /builds/Codistan/yourbakingconnection/baker-seller-panel/.env $HOSTNAME@$PUBLIC_KEY:/home/ubuntu/sp-test
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && npm install --legacy-peer-deps"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && sed -i 's/next start/PORT=4001 next start/g' package.json"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && npm run build"


deploy-test:
  only:
    - test
  stage: deploy
  before_script:
    - apt update
    - touch .env
    - mkdir ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - chmod 700 /root/.ssh
    - ssh-keyscan -H "$PUBLIC_KEY" >> ~/.ssh/known_hosts
#    - echo "$ENV_FILE_STAGING" > .env
  script:
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && git checkout test"
#    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && pm2 delete sp-test"
    - ssh -o StrictHostKeyChecking=no $HOSTNAME@$PUBLIC_KEY "cd /home/ubuntu/sp-test && pm2 start 'npm start' --name sp-test"
