mutation updateShop($input: UpdateShopInput!) {
  updateShop(input: $input) {
    shop {
      _id
      name
      description
      categories
      addressBook {
        address1
        city
        region
      }
      featuredShopImages {
        URLs {
          large
          medium
          original
        }
      }
    }
  }
}
