mutation LoginUserMutation($user: LoginUserInput!) {
  loginUser(user: $user) {
    shopId
    loginResult {
      tokens {
        refreshToken
        accessToken
      }

      sessionId
    }
  }
}
