query catalogItems(
  $shopIds: [ID]!
  $first: ConnectionLimitInt
  $offset: Int
  $sortBy: CatalogItemSortByField
  $sortOrder: SortOrder
) {
  catalogItems(
    shopIds: $shopIds
    first: $first
    offset: $offset
    sortBy: $sortBy
    sortOrder: $sortOrder
  ) {
    totalCount
    edges {
      node {
        ... on CatalogItemProduct {
          product {
            _id
            slug
            productId
            title
            description
            productAttributes {
              attribute
              options {
                optionLabel
                price
              }
            }
            productListingSchedule {
              startDate
              endDate
            }
            availableFulfillmentDates
            media {
              priority
              productId
              URLs {
                thumbnail
                large
                medium
                small
                original
              }
            }
            variants {
              variantId
              isTaxable
              inventoryInStock
              pricing {
                compareAtPrice {
                  amount
                  displayAmount
                }
                price
              }
            }
          }
        }
      }
    }
  }
}
