query customOrdersByShopQuery($first: ConnectionLimitInt, $offset: Int) {
  customOrdersByShop(first: $first, offset: $offset) {
    totalCount
    nodes {
      _id
      referenceId
      shopId
      # itemName
      email
      # phoneNumber
      quantity
      details
      createdAt
      updatedAt
      workflow
      fulfillmentDate
      orderByInfo {
        _id
        firstName
        lastName
        name
        primaryEmailAddress
        userId
      }
    }
  }
}
