query orders($shopIds: [ID]) {
  orders(shopIds: $shopIds) {
    edges {
      node {
        _id
        referenceId
        shop {
          name
        }
        summary {
          total {
            amount
          }
        }
        updatedAt
        account {
          firstName
          lastName
          primaryEmailAddress
        }
      }
    }
  }
}
