query baker($shopId: ID!) {
  baker(shopId: $shopId) {
    _id
    name
    slug
    description
    emails {
      address
    }
    shopLogoUrls {
      primaryShopLogoUrl
    }
    categories
    featuredShopImages {
      URLs {
        large
        medium
        small
        thumbnail
      }
    }
    addressBook {
      city
      region
    }
  }
}
