query bakers {
  bakers {
    nodes {
      _id
      name
      slug
      description
      shopLogoUrls {
        primaryShopLogoUrl
      }
      addressBook {
        city
        region
      }
    }
  }
}
