query catalogItemProductQuery($slugOrId: String!) {
  catalogItemProduct(slugOrId: $slugOrId) {
    _id
    product {
      _id
      title
      productId
      description
      productAttributes {
        attribute
        options {
          optionLabel
          price
        }
      }
      media {
        URLs {
          thumbnail
          large
        }
      }
      variants {
        variantId
        inventoryInStock
        pricing {
          compareAtPrice {
            amount
            displayAmount
          }
          price
        }
      }
    }
  }
}
