mutation createUserWithOtp($user: CreateUserInput!, $profile: UserProfileInput!) {
  bakerRegistration(user: $user, profile: $profile) {
    userId
    loginResult {
      tokens {
        refreshToken
        accessToken
      }
    }
  }
}
